### ISSUE TITLE
 Does biser suitable for plant SD detection? 

### ISSUE THREAD

**Issue by Chenglin20170390** [0xTCG/biser#10]
Dear  Ibrahim Numanagić,

   Many thanks for develop such useful tool.

    I wondering whether biser can detect SD for plant ? 
   I had try biser with my plant softmask genome, after  overlap duplicate SD region, the segment duplication detected by biser account for about 30% of my totol plant genome.

    I also try other software name asgart, it's report  about 3% SD of my totol genome.

    I compared two softwares for detecting the bases of SD and SD excluded TE. I had draw a simple figure for better understand what I mean.
<img width="860" alt="sdsdsd" src="https://user-images.githubusercontent.com/33062118/181592466-b2cfa798-9657-4340-b607-0373bb281efb.png">

**Comment by inumanag** [comment]
Hi @Chenglin20170390 

Yes, it should be suitable for that. Note that BISER uses 75% similarity instead of 90% typically used by other tools, so it's expected to see more results in BISER's output.

**Comment by Chenglin20170390** [comment]
Hi @inumanag ,

     Many thanks for you reply,  can we set the  parameter of biser similarity  to 90% ?  We would like to use it to  find the SD in plant genome.
     Thanks!

**Comment by inumanag** [comment]
Hi @Chenglin20170390 

In v1.3, you can do that! Add `--max-error=20 --max-edit-error=10`. Also, adding `--max_chromosome_size=100_000_000` might speed up the pipeline.
