### ISSUE TITLE
some cross-genome SD not found in "within genome" SD sets

### ISSUE THREAD

**Issue by hrrsjeong** [0xTCG/biser#12]
Hello! I ran biser using multiple genomes (different species) by feeding multiple fasta files. I found that there are some cross-species SDs (i.e., two different genome names split by ":" in column 7) that are not found in "within genome" SD sets (i.e., same genome names in column 7). I'm confused that how "not within genome SDs" can be found in cross-genome SDs. My understanding of "cross-genome SD" was that both genomes should include the region as SD within their genomes. Otherwise, all unique regions in two genomes can be cross-genome SDs. Please let me know if I don't understand it correctly.

I copied two example lines that found it as cross-genome SDs between CJ1700_CJA_hap1 and HG00733_hap1 genomes. These regions are not found in "within" HG00733_hap1 SDs (i.e., `HG00733_hap1.masked:HG00733_hap1.masked`)

```
chr12_RagTag	42834590	42835650	h2tg000009l	48945951	48946945	CJ1700_CJA_hap1_scaffold.masked:HG00733_hap1.masked	22.5	+	+	936	975	17M1D2M96S58M1D61M13D41M1D78M1D53M27I23N74M41I41N11M18D65M1D45M1D87M2D124M7N1M7S73M15I52M31N9M21S2M	X=9.9;ID=12.5
h2tg000009l	48945951	48946945	chr12_RagTag	60762975	60764017	HG00733_hap1.masked:CJ1700_CJA_hap1_scaffold.masked	21	+	-	925	955	2M21N15M1I55M1I66M13I41M1I19M1I112M27D23S74M14D41S12M9I73M1I45M1I87M2I124M7D7S74M15D44M96N8M31S11M	X=11.3;ID=9.7
```

**Comment by inumanag** [comment]
Hi @hrrsjeong 

I don't have access to these files—mind providing a source so that I can test it, together with the commands used? 

This is probably a bug; I guess that it happens because some of potential SD regions get filtered out during the intra-species SD step (due to the dissimilarity) the but not in the inter-species step (as that region is better conserved in the other species).

**Comment by inumanag** [comment]
Stashing this issue for now; might revisit it later on.

**Comment by zhoudreames** [comment]
Hi, @inumanag @hrrsjeong 
I also encountered a similar problem，Can this problem be solved？ Thanks~

**Comment by zuodabin** [comment]
Dear author, may I ask if this problem has been solved? In the subsequent versions?

**Comment by inumanag** [comment]
No, we have not addressed this as we were unable to reproduce the issue.
