### ISSUE TITLE
biser v1.3 cannot accept any input files

### ISSUE THREAD

**Issue by yangqimeng99** [0xTCG/biser#21]
hello，
I am using biser to detect SDs, but when I try to install biser v1.3 with pip install biser, no matter what file I input, even to a non-existent file, an error is thrown:
> `biser -o test.out -t 4 aaa.fa`
`ERROR: expected str, bytes or os.PathLike object, not NoneType`

biser v1.3 worked fine when I used biser -h

I reinstalled biser v1.2.3 and it works fine

**Comment by dgordon562** [comment]
ditto here.  Has anyone built from source and still get this problem?

**Comment by inumanag** [comment]
Hi @yangqimeng99 @dgordon562 

You can add `--temp .` to the BISER v1.3 to avoid this error. This issue is fixed on #19 ; the release will be merged soon.
