### ISSUE TITLE
BISER completed on soft_mask, but failed on hard_masked genome.

### ISSUE THREAD

**Issue by Weikai-47** [0xTCG/biser#22]
Hello,
During my experience, I met some questions:

The genome masking was performed using TRF and Repeatmasker according to this pipeline (Segmental duplications and their variation in a complete human genome, Science, 2022).
Then BISER v1.3 was ran on hard-mask and soft-mask genome, respectively. (biser --temp TMP -o DH.genome.hard -t 40 (--hard) --max-error=10 --max-edit-error=10 --max-chromosome-size=350000000 DH.genome.hard.fasta)

(1) BISER was successfully completed on soft_masked genome. 
Then I extracted the elementary SDs sequences from hard_mask genome based on the .elem.txt. The sequences looked like as this :
![image](https://user-images.githubusercontent.com/59557944/216802833-28208a1c-6acb-428b-8fd6-317a9de74763.png)

The elementary SDs were 337 Mb, with 63.7% masked repeats. Why ?

(2) BISER was failed at the step of  Putative SD detection on the hard_masked genome.
![SD elem](https://user-images.githubusercontent.com/59557944/216802925-bde05319-e807-4ece-aad9-b730b510de44.png)

Why the BISER failed on hard_masked genome ?

Thank You!
Chen

**Comment by inumanag** [comment]
1. This is expected--- BISER ignores repeats during the elementary SD generation (bu definition, elementary SDs are "older" than repeats so they are ignored). Repeats are later on superimposed on top of the hard-masked genome, so you should expect to see them in the final elementary SD set. They should be ignored during the analysis.

2. I don't know what is "hard-masked" genome in this context. Nevertheless, please use soft-masked version: BISER already does hard-masking that it needs automatically.
