### ISSUE TITLE
BISER failing during putative alignment step

### ISSUE THREAD

**Issue by docmanny** [0xTCG/biser#23]
Hello, 

We've been trying to run BISER on one of our genomes, and it consistently fails at the putative SD alignment step. The error is not consistent; rerunning it either fails at 0% or 5%. 0% fails without an error message, while 5% results in:

```
ERROR: BISER failed:
[p] /global/scratch/users/mvazquez/mambaforge/envs/biser/lib/python3.7/site-packages/biser/exe/biser.exe align /global/home/users/mvazquez/scratch/tmp/biser.d1v7gwfq/genomes/mMyoLuc1.cleaned.fa /global/home/users/mvazquez/scratch/tmp/biser.d1v7gwfq/align/mMyoLuc1.cleaned.00005.bed -o /global/home/users/mvazquez/scratch/tmp/biser.d1v7gwfq/align/mMyoLuc1.cleaned.00005.bed.align
```
I've confirmed that running SEDEF on the same genome leads to no issues. I tried digging around the temporary files and folders, and while I can confirm that there are BED files present in the `search` and `align` folders, there are no error messages or logs that can guide any further troubleshooting.

**Comment by inumanag** [comment]
Please try new version (v1.4) that provides lots of crash fixes.

Also, try adding `--gc-heap 1G` --- this is helpful on machines that have low ulimit settings (e.g., clusters).
