### ISSUE TITLE
Issue with building docker

### ISSUE THREAD

**Issue by aravindpad** [0xTCG/biser#24]
Hi,
I'm trying to build a docker for biser for our  cluster.
Getting stuck here.
Any help is much appreciated.
OS- Linux Debian 11 (64bit) building as root
Thank you

 > [17/20] RUN git clone -b codon https://github.com/0xTCG/biser /github/biser:
#0 0.454 Cloning into '/github/biser'...
#0 0.829 fatal: Remote branch codon not found in upstream origin
------
Dockerfile:55
--------------------
  53 |     # RUN cp /opt/codon-*.tar.bz2 /mnt/
  54 |
  55 | >>> RUN git clone -b codon https://github.com/0xTCG/biser /github/biser
  56 |     RUN python3 -m pip install --upgrade pip
  57 |     RUN python3 -m pip install --upgrade twine setuptools wheel
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone -b codon https://github.com/0xTCG/biser /github/biser" did not complete successfully: exit code: 128

**Comment by aravindpad** [comment]
My users are having issues with pip version. That's why I'm building the docker.
Thanks

**Comment by aravindpad** [comment]
Any help?

**Comment by inumanag** [comment]
Hi @aravindpad 

Replace `git clone -b codon` with `git clone`; it should work then.

**Comment by inumanag** [comment]
Fixed in the latest commit.
