### ISSUE TITLE
biser failed -6 

### ISSUE THREAD

**Issue by jix2010** [0xTCG/biser#25]
Thank you for sharing this great tool for detecting SDs. I successfully finished hard-masking, putative SD detection, putative SD alignment and SD decomposition, but then got an error saying Biser failed (-6) 
ESC[1mI0Error: ESC[0mfile /myfilelocation/SD/ could not be opened

I'm pretty sure that the above directory exists. Could you please help me debug this? Thank you!

**Comment by inumanag** [comment]
Hi @jix2010 

Can you please share the command with me and the full output?

**Comment by inumanag** [comment]
Hi @WK-yjf,

You need to remove `/` at the end of output (i.e., it should be `-o /data/LiY/disk/YJF/SDs_output` and not `/data/LiY/disk/YJF/SDs_output/`). BISER outputs a file, not a directory.
