### ISSUE TITLE
ERROR: BISER failed (-9):

### ISSUE THREAD

**Issue by dorachu625** [0xTCG/biser#26]
Hi，when I ran BISER v1.4 on one genome,  it failed with an error "ERROR: BISER failed (-9)". How to solve this problem? Thank you so much.  
Command is as follows:
biser -o new.sd -t 20  --gc-heap 1G  --keep-contigs genome.fa

file genome.fa is soft-maskered and indexed with samtools.

**Comment by inumanag** [comment]
Hi @dorachu625 

One way is to add `--gc-heap` to the run and lower the number of threads (see #29 for details). Try `-t 2` and `--gc-heap 10G`.

Which genome you are analyzing? Some genomes---especially ones that are not filtered---are tricky. I suggest doing RepMasker first with _the complete uncurated dfam_ before running BISER on contig genomes (note: RepMasker might take from a day to weeks to complete depending on the genome). This will _tremendously_ speed up BISER and improve the quality of calls.

**Comment by shokrof** [comment]
I am trying to run BISER on Bos Taurus masked genome from this link (https://hgdownload.soe.ucsc.edu/goldenPath/bosTau9/bigZips/bosTau9.fa.masked.gz)  and I am getting -9 error. I have tried setting --gc-heap to 2,10,200,400GB, also I tried to decrease the number of threads to 2.
I am running on an HPC cluster running on Linux.
