### ISSUE TITLE
how to decomposing segmental duplications (SDs) when i have the SDs annotation files.

### ISSUE THREAD

**Issue by zhoudreames** [0xTCG/biser#27]
I want to look into the shared and unique SDs for three genomes； I had annotated these genomes using sedef and filter them based on customed standards.  Then, I  only want to decompose SDs by using the SD annotation files instead of using the whole workflow. Can I do this? Thanks~

**Comment by inumanag** [comment]
Hi @zhoudreames 

BISER won't work with SEDEF annotations. I'd suggest running BISER either individually on each of them, or (even better) jointly on all of them. It should not take more than a day.
