### ISSUE TITLE
Cannot modify the max error value when running biser

### ISSUE THREAD

**Issue by yangyxt** [0xTCG/biser#28]
![image](https://user-images.githubusercontent.com/40780228/231469426-19dadf0e-e539-4282-88ca-84199c0ee54d.png)

**Comment by inumanag** [comment]
Hi @yangyxt 

Which version of BISER you are using? This is only supported in the latest version.

**Comment by yangyxt** [comment]
@inumanag Thanks for the response. 

I just managed to build biser from github and package it into a docker image: https://hub.docker.com/repository/docker/yangyxt/biser/general

By far, I have several inquiries regarding the latest version:
1. what are the scores referring to in the result table, whats the specific calculation of it ? 
2. Can we have a decomposed SD binary map ? With a metric stat their similarity ? 
3. Can we have further explanation about how the arguments values help control the decomposition of the SD intervals? 

Much appreciated!

**Comment by inumanag** [comment]
1. Which scores? The explanation is outlined in the README; if it is not clear, please tell me which needs further clarification.
2. I do not understand what would that be, but in either case, it's unlikely that I will be able to add a major feature for the time being. Would be happy to accept PRs, though.
3. Currently, decomposition is not parametrizable by an end-user. You will have to tweak https://github.com/0xTCG/biser/blob/master/biser/codon/decompose.codon for that; some parametrization experiments are done here: https://dspace.library.uvic.ca/handle/1828/13343, but for more details, you will have to tune the parameters yourself.
