### ISSUE TITLE
install BISER (Error)

### ISSUE THREAD

**Issue by saraebell** [0xTCG/biser#3]
I am having issues with 'pip install git+https://github.com/0xTCG/biser.git'
I believe I have successfully installed Seq programming language. I am unsure what the main issues is and where I can look to try and fix it. Any suggestions would be appreciated. Thank you in advance. 
![Screen Shot 2022-03-01 at 9 28 09 AM](https://user-images.githubusercontent.com/82554600/156218748-73be1d41-152c-48c6-b043-2f32479e2fe5.png)
![Screen Shot 2022-03-01 at 9 31 44 AM](https://user-images.githubusercontent.com/82554600/156218933-13366179-bd18-4ed3-8f54-8d7f0a433d99.png)

**Comment by inumanag** [comment]
Hi @saraebell,

Thank you for the report. Can you please tell me which OS / environment do you use?

**Comment by saraebell** [comment]
@inumanag Thank you for your response, yes, I am on a university HPC running CentOS 7.

**Comment by Jingwen7** [comment]
Hi @inumanag ,

I have the same issue when installing BISER on HPC.

**Comment by m-jahani** [comment]
Hi @inumanag ,

I have the same issue with installing BISER on ubuntu 20.03

**Comment by heyaoxi** [comment]
Me too! Any solution?

**Comment by inumanag** [comment]
Apologies for the delay. Please try installing pre-compiled wheel by doing `pip install biser`. Let me know if this works.

**Comment by inumanag** [comment]
Closing the issue as this seems resolved.
