### ISSUE TITLE
How to run biser

### ISSUE THREAD

**Issue by aravindpad** [0xTCG/biser#30]
Hi,
Thank you for fixing my previous issue. I was able to build the container and run it to a sh.
As I'm an admin setting up this on the cluster for a user, could you please update how to run the 'biser' as I could not find an executable for the application.
Thank you

**Comment by aravindpad** [comment]
Hi Any help

**Comment by inumanag** [comment]
Hi @aravindpad 

The best way to do this is to issue `pip install biser` (in a Linux container environment, if you prefer) and then just run `biser [args]` or `python -m biser [args]`.

**Comment by aravindpad** [comment]
> Hi @aravindpad
> 
> The best way to do this is to issue `pip install biser` (in a Linux container environment, if you prefer) and then just run `biser [args]` or `python -m biser [args]`.

Hi,
I was following instructions on the docker build. Looks like the docker has only windows binary right. Ok thank you for the info. I'll just do pip install.
I was under the impression that biser was already per-installed in the docker.
Thanks

**Comment by inumanag** [comment]
No, Windows is not supported by BISER. Only Linux binaries are available. 

Instead of using the provided Dockerfile which is intended for from-scratch compilation, I'd suggest just using `pip install`--- much easier to build and deploy.

**Comment by aravindpad** [comment]
Hi,
Thank you. I just found an exe for biser so i thought it's supported.
sh-4.2# cd /github/biser/build/lib/biser/exe
sh-4.2# ls
biser.exe  libcodonrt.so  libomp.so
sh-4.2#

My users were facing issues with pip install, that's why I thought about trying out the docker. I was able to get the docker running but it was missing the binary.
Thanks for your help. I'll pip install biser in the docker.

**Comment by inumanag** [comment]
`biser.exe` is linux executable; the extension is bit misleading, though :)

**Comment by aravindpad** [comment]
Oh That's good to know, in that case I can try to run it :-)
