### ISSUE TITLE
ERROR ：BISER failed (-11)

### ISSUE THREAD

**Issue by jiangjiang030** [0xTCG/biser#33]
my command is : biser -o T2T-CHM13_output -t 2 --keep-contigs --hard  T2T-CHM13.fna.masked --gc-heap 2G

Running BISER v1.4 on 1 genome(s): T2T-CHM13.fna

1. Putative SD detection
  0%|                                        | 0/24
ERROR: BISER failed (-11):
[p] /root/data2/jiang2023/miniconda3/envs/biser/lib/python3.12/site-packages/biser/exe/biser.exe search /root/data2/jiang2023/miniconda3/envs/repeat/share/RepeatMasker/h_result/T2T-CHM13.fna.masked -c NC_060925.1 -o /tmp/biser.r20y75wh/search/T2T-CHM13.fna_NC_060925.1_0.bed 0 --kmer-size=14 --winnow-size=16 --max-error=0.3 --max-edit-error=0.15 --max-chromosome-size=300000000
[o]
[e]

My input has been hard-masked, so I add the command "--hard". I have reviewed similar issues with others and after adding the "--gc-heap 2G" command, there are still errors.
I don't know how to modify it in order for it to run properly. Thanks very much.

**Comment by ld9866** [comment]
@jiangjiang030  Hello，how you solve this problem?
