### ISSUE TITLE
genotype same segdups across individuals

### ISSUE THREAD

**Issue by svedwards** [0xTCG/biser#38]
How would you recommend genotyping an array of individuals with sds called from a reference genome? Should we put all the genomes into the command line (alot - in my case, 90 separate haplotypes) or can we run them along with the reference in a pairwise fashion? Thanks for your recommendation

**Comment by inumanag** [comment]
Ho @svedwards 

BISER is designed to compare different reference genomes, not different haplotypes (I mean, in theory you can do that, but I expect that you'll get nearly identical SDs). 

I'd honestly here go with individual SD detection (90 separate invocations of BISER) and then would try to analyze the differences manually. You also need to repeat-mask haplotypes if you want to go down this route.
