### ISSUE TITLE
How to measure the length and frequency of Whole-Genome segmental duplications (SDs)?

### ISSUE THREAD

**Issue by kuangzhuoran** [0xTCG/biser#39]
Are SD mates considered as SDs?

If SD mates are also considered as SDs, then the first six columns of the output file will all represent SDs. 
I just need to extract these six columns and calculate their sum.

**Comment by T-164321** [comment]
@kuangzhuoran ,老师，您好。您最终怎么确定SD在全基因组中有多少Mb？

**Comment by kuangzhuoran** [comment]
awk '{OFS="\t"; print $1,$2,$3"\n"$4,$5,$6}' biserdups.bedpe | bedtools merge > biserdups.bed

This is copied from the GitHub of some software related to repeat sequence processing, but I forgot which specific software it is.

**Comment by T-164321** [comment]
@kuangzhuoran 非常感谢老师的回答，awk '{OFS="\t"; print $1,$2,$3"\n"$4,$5,$6}' biserdups.bedpe | bedtools merge > biserdups.bed  这也同样适用于BISER这个软件吗？

**Comment by kuangzhuoran** [comment]
biserdups.bed就是BISER的两个输出文件之一，不是*.elem.txt

**Comment by T-164321** [comment]
@kuangzhuoran 好的，谢谢老师，那输出结果文件biserdups.bed就是SD的大小吗？

**Comment by kuangzhuoran** [comment]
不好意思, biserdups.bedpe才是输出文件之一，刚刚写错了

#获取SD的基因组坐标
awk '{OFS="\t"; print $1,$2,$3"\n"$4,$5,$6}' biserdups.bedpe | bedtools merge > biserdups.bed

#对SD的长度求和
awk '{print $3-$2}' | awk '{sum += $1};END {print sum}' biserdups.bed

**Comment by T-164321** [comment]
@kuangzhuoran 好的老师，biserdups.bedpe 这个是文件是BISER输出文件(不是*.elem.txt)。awk '{print $3-$2}' | awk '{sum += $1};END {print sum}' biserdups.bed 这个命令才是计算SD的大小，我理解的对吗？

**Comment by kuangzhuoran** [comment]
你好，是的
