### ISSUE TITLE
I/O error Raised from: std.internal.file.File.__init__.3 [e] /home/vagrant/.seq/lib/seq/stdlib/internal/file.seq:14:13

### ISSUE THREAD

**Issue by jmkidd** [0xTCG/biser#4]
Hi,
I've installed biser using pip install biser in a conda environment running python 3.7.  When running biser i get a file I/O error an a reference to /home/vagrant/.seq/lib/seq/stdlib/internal/file.seq.

Could you help troubleshoot?  Is there something wrong with the prebuilt pip package?

Here is the info printed.
Thanks
Jeff

Running BISER on 1 genome(s): mCanLor1.2.masked

0. Hard-masking genomes
100%|████████████████████████████████████████| 1/1
  Hard-masking: 01:05s (single: 01:00s)

1. Putative SD detection
100%|████████████████████████████████████████| 40/40
  Search: 03:40s (single: 28:46s)

2. Putative SD alignment
100%|████████████████████████████████████████| 50/50
  Align: 11:13s (single: 58:13s)

3. SD decomposition
100%|████████████████████████████████████████| 2621/2621
  Decomposition: 03:22s (single: 04:25s)
ERROR: BISER failed:
[p] /home/jmkidd/links/kidd-lab-scratch/jmkidd-projects/miniconda3/envs/biserENV/lib/python3.9/site-packages/biser/exe/biser.exe translate -o mCanLor1.2-BISER.out.bed /nfs/turbo/jmkidddata/jmkidd-projects/people-projects/anthony-projects/test-BISER/biser-temp/biser7htlmq2n/final.bed /nfs/turbo/jmkidddata/jmkidd-projects/people-projects/anthony-projects/test-BISER/mCanLor1.2.masked.fasta
[o] 
[e] Loading took 10.8591s
[e] Translating took 0.00149958s
[e] Translate took 10.8607s
[e] IOError: file /nfs/turbo/jmkidddata/jmkidd-projects/people-projects/anthony-projects/test-BISER/biser-temp/biser7htlmq2n/final.bed could not be opened
[e] 
[e] Raised from: std.internal.file.File.__init__.3
[e] /home/vagrant/.seq/lib/seq/stdlib/internal/file.seq:14:13

**Comment by jmkidd** [comment]
Update: if I use the --keep-temp option it seems to run fine.

**Comment by inumanag** [comment]
Let me take a look. Thanks for the report.

**Comment by inumanag** [comment]
Fixed. Please try v1.1 (should be available through pip).

**Comment by saraebell** [comment]
updating to v1.1 solved this issue for me, thank you.
