### ISSUE TITLE
mismatch rate

### ISSUE THREAD

**Issue by hrrsjeong** [0xTCG/biser#7]
Hello @inumanag 
I have a quick question regarding the optional field from the biser output. Is mismatch rate (start with X=) computed by `mismatch count / (match count + mismatch count)` or `mismatch count / aln_len (including gaps)`. Similarly, could you please let me know you used the same denominator when you compute the mismatch rate (`X=`) and gap rate (`ID=`)? I assume they are similar to `1 - fracMatch` and `1 - fracMatchIndel` in SEDEF, but it would be great if you confirm this.

Also, I would like to compare the results between `biser` and `sedef`. I found that `biser` output doesn't provide `alnB`, `matchB`, `mismatchB` in `sedef` output. I was wondering if there's a way to extract this information. I tried using sum of length of `M` in CIGAR string divided by mismatch, but again how to compute the mismatch rate (`X=`) in the optional field wasn't clear. Thanks so much!!

**Comment by inumanag** [comment]
Here are the details:
https://github.com/0xTCG/biser/blob/39df972995c2fe19563be6d3408e4fcadb08ea61/biser/seq/hit.seq#L200

so it should be `aln_len`.

I cannot recall exactly how SEDEF generated that info. The exact procedure that does it can be found here:
https://github.com/vpc-ccg/sedef/blob/5acd139436fe823302f27b7a526299da6db8034f/src/stats_main.cc#L245

**Comment by hrrsjeong** [comment]
sorry for my late response and thanks for your information. One quick question. Following your information, I tried to get the number of mismatch resulting from mismatch rate (`X=3.2` from the example below) and aln_len (`2739` from the example below) as `(mismatch rate / 100) * aln_len` which is `(3.2 / 100) * 2739 = 87.648`. Do you by any chance know why the number is not integer? I tried other lines too but it almost always not giving me integers. 

```
h2tg000001l     1816544 1819666 h2tg000001l     1944172 1947036 HG00733_hap1.masked:HG00733_hap1.masked 14.2    +       +   2679     2739    275M224D1M224S202M19S19N25M20S20N108M8I1M31N1M23S316M1I47M20I20N25M17D40M9I13M20N3M21I80M1D239M1I510M21S21N32
4M31S31N10M23S23N217M   X=3.2;ID=11
```

**Comment by hrrsjeong** [comment]
I just found it from the code that `hit.span()` sums up all the numbers in cigar string, so it seems like it's not just `aln_len` but also including all insertion/deletion/segment/softclipped etc.
