### ISSUE TITLE
BEDPE fields in output

### ISSUE THREAD

**Issue by saraebell** [0xTCG/biser#8]
First, thank you for creating an easy to use tool for detecting segmental duplications.

I have successfully generated results using the BISER tool, but I noticed the output BEDPE file does not include the Field **names** when it is generated  (neither does the elem.txt). Is there a way for the Field **names** to be included when generating the output BEDPE file? Thank you!

**First 3 lines of output BEDPE file**
```
chr1	3042602	3044990	chr1	45613987	45616318	mm9:mm9	6.4	+	+	1091	1102	4M1162S1102N141M2I113M9I35M138S138N690M13D39M1D55M	X=4.1;ID=2.3
chr1	3135187	3137396	chr1	28229835	28232644	mm9:mm9	19.5	+	+	985	986	249M24I137S161N26M119S119N12M90S91N13M113S113N5M43I442S481N112M88I37S1I286S3I363N284M1D125M	X=3.2;ID=16.2
chr1	5099409	5104076	chr1	5100098	5104638	mm9:mm9	37.5	+	+	4667	5590	42M113D37M1I114M1I23M1I32M1I56M1I81M1I57M171I30M1I26M1I32M1I56M1I56M1I80M1I258M1I110M1D58M1D56M1D56M1D57M1D112M1D24M1D32M1D56M1D21M57D35M1D227M1I114M1I134M113D66M1I165M172D203M1D56M1I56M1D56M1I257M1D48M113D38M286D79M456I90M1D172M284I22M55D207M114I6M7I24M	X=2.3;ID=35.3	
```

**Comment by inumanag** [comment]
Hi @saraebell 

The name field is there: it is `mm9:mm9` in this example and it is used to indicate reference genomes (typically `genome:genome` if you run BISER on a single genome). Let me know if this is not what you had in mind.
